platform :ios, '7.0'
inhibit_all_warnings!

target 'WQRoute_Example' do
    pod 'WQRoute', :path => '../'
    pod 'AFNetworking'
    pod 'SVProgressHUD'
    
    target 'WQRoute_Tests' do
        inherit! :search_paths
        
        pod 'Kiwi'
    end
end
